import { Entity, PrimaryGeneratedColumn, OneToMany, Column } from 'typeorm';
import { UserRole } from './user_role.entity';

// Make sure to add aditional roles here then reseed
export enum RoleKey {
  // base roles
  ADMIN = 'admin',
  USER = 'user',
  // system roles
  SYS_SYSADMIN = 'urn:lti:sysrole:ims/lis/SysAdmin',
  SYS_SUPPORT = 'urn:lti:sysrole:ims/lis/SysSupport',
  SYS_CREATOR = 'urn:lti:sysrole:ims/lis/Creator',
  SYS_ACCOUNTADMIN = 'urn:lti:sysrole:ims/lis/AccountAdmin',
  SYS_USER = 'urn:lti:sysrole:ims/lis/User',
  SYS_ADMINISTRATOR = 'urn:lti:sysrole:ims/lis/Administrator',
  SYS_NONE = 'urn:lti:sysrole:ims/lis/None',
  // institutional roles
  INST_STUDENT = 'urn:lti:instrole:ims/lis/Student',
  INST_FACULTY = 'urn:lti:instrole:ims/lis/Faculty',
  INST_MEMBER = 'urn:lti:instrole:ims/lis/Member',
  INST_LEARNER = 'urn:lti:instrole:ims/lis/Learner',
  INST_INSTRUCTOR = 'urn:lti:instrole:ims/lis/Instructor',
  INST_MENTOR = 'urn:lti:instrole:ims/lis/Mentor',
  INST_STAFF = 'urn:lti:instrole:ims/lis/Staff',
  INST_ALUMNI = 'urn:lti:instrole:ims/lis/Alumni',
  INST_PROSPECTIVESTUDENT = 'urn:lti:instrole:ims/lis/ProspectiveStudent',
  INST_GUEST = 'urn:lti:instrole:ims/lis/Guest',
  INST_OTHER = 'urn:lti:instrole:ims/lis/Other',
  INST_ADMINISTRATOR = 'urn:lti:instrole:ims/lis/Administrator',
  INST_OBSERVER = 'urn:lti:instrole:ims/lis/Observer',
  INST_NONE = 'urn:lti:instrole:ims/lis/None',
  // context roles
  CONTEXT_LEARNER = 'urn:lti:role:ims/lis/Learner',
  CONTEXT_LEARNER_LEARNER = 'urn:lti:role:ims/lis/Learner/Learner',
  CONTEXT_LEARNER_NONCREDITLEARNER = 'urn:lti:role:ims/lis/Learner/NonCreditLearner',
  CONTEXT_LEARNER_GUESTLEARNER = 'urn:lti:role:ims/lis/Learner/GuestLearner',
  CONTEXT_LEARNER_EXTERNALLECTURER = 'urn:lti:role:ims/lis/Learner/ExternalLearner',
  CONTEXT_LEARNER_INSTRUCTOR = 'urn:lti:role:ims/lis/Learner/Instructor',
  CONTEXT_INSTRUCTOR = 'urn:lti:role:ims/lis/Instructor',
  CONTEXT_INSTRUCTOR_PRIMARYINSTRUCTOR = 'urn:lti:role:ims/lis/Instructor/PrimaryInstructor',
  CONTEXT_INSTRUCTOR_LECTURER = 'urn:lti:role:ims/lis/Instructor/Lecturer',
  CONTEXT_INSTRUCTOR_GUESTINSTRUCTOR = 'urn:lti:role:ims/lis/Instructor/GuestInstructor',
  CONTEXT_INSTRUCTOR_EXTERNALINSTRUCTOR = 'urn:lti:role:ims/lis/Instructor/ExternalInstructor',
  CONTEXT_CONTENT_DEVELOPER = 'urn:lti:role:ims/lis/ContentDeveloper',
  CONTEXT_CONTENT_DEVELOPER_CONTENT_DEVELOPER = 'urn:lti:role:ims/lis/ContentDeveloper/ContentDeveloper',
  CONTEXT_CONTENT_DEVELOPER_LIBRARIAN = 'urn:lti:role:ims/lis/ContentDeveloper/Librarian',
  CONTEXT_CONTENT_DEVELOPER_CONTENTEXPERT = 'urn:lti:role:ims/lis/ContentDeveloper/ContentExpert',
  CONTEXT_CONTENT_DEVELOPER_EXTERNALCONTENTEXPERT = 'urn:lti:role:ims/lis/ContentDeveloper/ExternalContentExpert',
  CONTEXT_MEMBER = 'urn:lti:role:ims/lis/Member',
  CONTEXT_MEMBER_MEMBER = 'urn:lti:role:ims/lis/Member/Member',
  CONTEXT_MANAGER = 'urn:lti:role:ims/lis/Manager',
  CONTEXT_MANAGER_AREAMANAGER = 'urn:lti:role:ims/lis/Manager/AreaManager',
  CONTEXT_MANAGER_COURSECOORDINATOR = 'urn:lti:role:ims/lis/Manager/CourseCoordinator',
  CONTEXT_MANAGER_OBSERVER = 'urn:lti:role:ims/lis/Manager/Observer',
  CONTEXT_MANAGER_EXTERNALOBSERVER = 'urn:lti:role:ims/lis/Manager/ExternalObserver',
  CONTEXT_MENTOR = 'urn:lti:role:ims/lis/Mentor',
  CONTEXT_MENTOR_MENTOR = 'urn:lti:role:ims/lis/Mentor/Mentor',
  CONTEXT_MENTOR_REVIEWER = 'urn:lti:role:ims/lis/Mentor/Reviewer',
  CONTEXT_MENTOR_ADVISOR = 'urn:lti:role:ims/lis/Mentor/Advisor',
  CONTEXT_MENTOR_AUDITOR = 'urn:lti:role:ims/lis/Mentor/Auditor',
  CONTEXT_MENTOR_TUTOR = 'urn:lti:role:ims/lis/Mentor/Tutor',
  CONTEXT_MENTOR_LEARNINGFACILITATOR = 'urn:lti:role:ims/lis/Mentor/LearningFacilitator',
  CONTEXT_MENTOR_EXTERNALMENTOR = 'urn:lti:role:ims/lis/Mentor/ExternalMentor',
  CONTEXT_MENTOR_EXTERNALREVIEWER = 'urn:lti:role:ims/lis/Mentor/ExternalReviewer',
  CONTEXT_MENTOR_EXTERNALADVISOR = 'urn:lti:role:ims/lis/Mentor/ExternalAdvisor',
  CONTEXT_MENTOR_EXTERNALAUDITOR = 'urn:lti:role:ims/lis/Mentor/ExternalAuditor',
  CONTEXT_MENTOR_EXTERNALTUTUR = 'urn:lti:role:ims/lis/Mentor/ExternalTutor',
  CONTEXT_MENTOR_EXTERNALLEARNINGFACILITATOR = 'urn:lti:role:ims/lis/Mentor/ExternalLearningFacilitator',
  CONTEXT_ADMINISTRATOR = 'urn:lti:role:ims/lis/Administrator',
  CONTEXT_ADMINISTRATOR_ADMINISTRATOR = 'urn:lti:role:ims/lis/Administrator/Administrator',
  CONTEXT_ADMINISTRATOR_SUPPORT = 'urn:lti:role:ims/lis/Administrator/Support',
  CONTEXT_ADMINISTRATOR_DEVELOPER = 'urn:lti:role:ims/lis/Administrator/Developer',
  CONTEXT_ADMINISTRATOR_SYSTEMADMINISTRATOR = 'urn:lti:role:ims/lis/Administrator/SystemAdministrator',
  CONTEXT_ADMINISTRATOR_EXTERNALSYSTEMADMINISTRATOR = 'urn:lti:role:ims/lis/Administrator/ExternalSystemAdministrator',
  CONTEXT_ADMINISTRATOR_EXTERNALDEVELOPER = 'urn:lti:role:ims/lis/Administrator/ExternalDeveloper',
  CONTEXT_ADMINISTRATOR_EXTERNALSUPPORT = 'urn:lti:role:ims/lis/Administrator/ExternalSupport',
  CONTEXT_TEACHINGASSISTANT = 'urn:lti:role:ims/lis/TeachingAssistant',
  CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANT = 'urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistant',
  CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTSECTION = 'urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantSection',
  CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTSECTIONASSOCIATION = 'urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantSectionAssociation',
  CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTOFFERING = 'urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantOffering',
  CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTTEMPLATE = 'urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantTemplate',
  CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTGROUP = 'urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantGroup',
  CONTEXT_TEACHINGASSISTANT_GRADER = 'urn:lti:role:ims/lis/TeachingAssistant/Grader',
}

@Entity()
export class Role {
  static ROLES = [
    RoleKey.ADMIN,
    RoleKey.USER,
    RoleKey.SYS_SYSADMIN,
    RoleKey.SYS_SUPPORT,
    RoleKey.SYS_CREATOR,
    RoleKey.SYS_ACCOUNTADMIN,
    RoleKey.SYS_USER,
    RoleKey.SYS_ADMINISTRATOR,
    RoleKey.SYS_NONE,
    // institutional roles
    RoleKey.INST_STUDENT,
    RoleKey.INST_FACULTY,
    RoleKey.INST_MEMBER,
    RoleKey.INST_LEARNER,
    RoleKey.INST_INSTRUCTOR,
    RoleKey.INST_MENTOR,
    RoleKey.INST_STAFF,
    RoleKey.INST_ALUMNI,
    RoleKey.INST_PROSPECTIVESTUDENT,
    RoleKey.INST_GUEST,
    RoleKey.INST_OTHER,
    RoleKey.INST_ADMINISTRATOR,
    RoleKey.INST_OBSERVER,
    RoleKey.INST_NONE,
    // context roles
    RoleKey.CONTEXT_LEARNER,
    RoleKey.CONTEXT_LEARNER_LEARNER,
    RoleKey.CONTEXT_LEARNER_NONCREDITLEARNER,
    RoleKey.CONTEXT_LEARNER_GUESTLEARNER,
    RoleKey.CONTEXT_LEARNER_EXTERNALLECTURER,
    RoleKey.CONTEXT_LEARNER_INSTRUCTOR,
    RoleKey.CONTEXT_INSTRUCTOR,
    RoleKey.CONTEXT_INSTRUCTOR_PRIMARYINSTRUCTOR,
    RoleKey.CONTEXT_INSTRUCTOR_LECTURER,
    RoleKey.CONTEXT_INSTRUCTOR_GUESTINSTRUCTOR,
    RoleKey.CONTEXT_INSTRUCTOR_EXTERNALINSTRUCTOR,
    RoleKey.CONTEXT_CONTENT_DEVELOPER,
    RoleKey.CONTEXT_CONTENT_DEVELOPER_CONTENT_DEVELOPER,
    RoleKey.CONTEXT_CONTENT_DEVELOPER_LIBRARIAN,
    RoleKey.CONTEXT_CONTENT_DEVELOPER_CONTENTEXPERT,
    RoleKey.CONTEXT_CONTENT_DEVELOPER_EXTERNALCONTENTEXPERT,
    RoleKey.CONTEXT_MEMBER,
    RoleKey.CONTEXT_MEMBER_MEMBER,
    RoleKey.CONTEXT_MANAGER,
    RoleKey.CONTEXT_MANAGER_AREAMANAGER,
    RoleKey.CONTEXT_MANAGER_COURSECOORDINATOR,
    RoleKey.CONTEXT_MANAGER_OBSERVER,
    RoleKey.CONTEXT_MANAGER_EXTERNALOBSERVER,
    RoleKey.CONTEXT_MENTOR,
    RoleKey.CONTEXT_MENTOR_MENTOR,
    RoleKey.CONTEXT_MENTOR_REVIEWER,
    RoleKey.CONTEXT_MENTOR_ADVISOR,
    RoleKey.CONTEXT_MENTOR_AUDITOR,
    RoleKey.CONTEXT_MENTOR_TUTOR,
    RoleKey.CONTEXT_MENTOR_LEARNINGFACILITATOR,
    RoleKey.CONTEXT_MENTOR_EXTERNALMENTOR,
    RoleKey.CONTEXT_MENTOR_EXTERNALREVIEWER,
    RoleKey.CONTEXT_MENTOR_EXTERNALADVISOR,
    RoleKey.CONTEXT_MENTOR_EXTERNALAUDITOR,
    RoleKey.CONTEXT_MENTOR_EXTERNALTUTUR,
    RoleKey.CONTEXT_MENTOR_EXTERNALLEARNINGFACILITATOR,
    RoleKey.CONTEXT_ADMINISTRATOR,
    RoleKey.CONTEXT_ADMINISTRATOR_ADMINISTRATOR,
    RoleKey.CONTEXT_ADMINISTRATOR_SUPPORT,
    RoleKey.CONTEXT_ADMINISTRATOR_DEVELOPER,
    RoleKey.CONTEXT_ADMINISTRATOR_SYSTEMADMINISTRATOR,
    RoleKey.CONTEXT_ADMINISTRATOR_EXTERNALSYSTEMADMINISTRATOR,
    RoleKey.CONTEXT_ADMINISTRATOR_EXTERNALDEVELOPER,
    RoleKey.CONTEXT_ADMINISTRATOR_EXTERNALSUPPORT,
    RoleKey.CONTEXT_TEACHINGASSISTANT,
    RoleKey.CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANT,
    RoleKey.CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTSECTION,
    RoleKey.CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTSECTIONASSOCIATION,
    RoleKey.CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTOFFERING,
    RoleKey.CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTTEMPLATE,
    RoleKey.CONTEXT_TEACHINGASSISTANT_TEACHINGASSISTANTGROUP,
    RoleKey.CONTEXT_TEACHINGASSISTANT_GRADER,
  ];

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  key: RoleKey;

  @OneToMany(() => UserRole, (userRole) => userRole.role)
  userRoles: UserRole[];
}
